config/routes.rb
 PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do 
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end 
    end

  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/post.rb
class Post < ActiveRecord::Base
  PER_PAGE = 7

  include VoteableTimBeiko
  include Slugable

  default_scope { order('created_at ASC')}

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true, length: {minimum: 3}
  validates :url, presence: true, uniqueness: true
  validates :description, presence: true

  slugable_column :title

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Set up an instance variable for action (or redirect based on some condition)
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  before_action :require_creator, only: [:edit, :update]


  def index
    @posts = Post.all.sort_by{|x| x.total_votes}.reverse[params[:offset].to_i, Post::PER_PAGE]
    @pages = (Post.all.size / Post::PER_PAGE)
    @pages += 1 if (Post.all.size % Post::PER_PAGE) > 0 
  end

  def show
    @comment = Comment.new
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.creator = current_user 

    if @post.save
      flash[:notice] = "Your post was created."
      verify_if_moderator
      redirect_to posts_path
    else 
      render :new
    end
  end

  def edit 
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "The post was updated successfully."
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.save
          flash[:notice] = "Your vote was counted."
        else
          flash[:error] = "You've already voted on '#{@post.title}'."
        end
        redirect_to :back
      end

      format.js
    end
  end




   
  private
    def post_params
      params.require(:post).permit(:title, :url, :description, :user_id, category_ids: [])
    end

    def set_post
      @post = Post.find_by(slug: params[:id])
    end 

    def require_creator
      access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
    end

end

app/views/posts/_comments.html.erb
<div class='row'>
  <div class='span0 well text-center'>
    <% if logged_in? %> 
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post' do %>
        <i class='icon-arrow-up'></i>
      <% end %><br/>
    <% end %>
    <%= comment.total_votes %> Votes</br>
    <% if logged_in? %> 
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post' do %>
        <i class='icon-arrow-down'></i>
      <% end %></br>
    <% end %>
  </div>
  
  <div class='well span8'>
    <em>"<%= comment.body %>"</em></br>
    <% if @user %>
      <small> on <%= link_to comment.post.title, post_path(comment.post) %></small>
    <% end %>
    <small>posted by: <%= link_to comment.creator.username, user_path(comment.creator)%> on <%= display_datetime(comment.created_at) %></small>
  </div>
</div>

app/views/posts/_form.html.erb
<%= render 'shared/errors', entry: @post %>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <br/>
  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>
  <br/>

  <div class='control-group'>
    <%= f.label 'Categories' %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>

  <br/>
  <%= f.submit(@post.new_record? ? "Create Post" : 'Update Post', class: "btn btn-primary") %>
<% end %>

app/views/posts/_post.html.erb
<div class="row">
  <div id="post_vote_error_<%= post.to_param %>" class="alert alert-error" style="display: none">
    You can only vote on this post once!
  </div>
  <div class='span0 well text-center'>
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
  <br/>
  <span id='post_<%= post.slug %>_votes'><%=post.total_votes %> Votes</span></br>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>  
    <% end %>
  </div>
  <div class='span8 well'>
    <%= render post.categories %>

    <h4><%= link_to post.title, fix_url(post.url)%></h4> 
    <p><%= post.description %></p>
    <p>
      <span class='quiet'>posted by</span> <%= link_to post.creator.username, user_path(post.creator) %> 
      <small>on <%= display_datetime(post.created_at) %></small>
    </p>
    <small>
    <span>
      <%= link_to("#{post.comments.count} comments", post_path(post)) %>
    </span>
    <% if logged_in? && post.creator == current_user %>
      <span>
        (<%= link_to 'edit', edit_post_path(post) %>)
      </span>
    <% elsif logged_in? && current_user.admin? %>
      (<%= link_to 'edit', edit_post_path(post) %>)
    <% end %>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit this Post' %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

<div class='center-block'>
  <h5 class='center-block'>
  <% @pages.times do |n| %>
    <% if (params[:offset].nil? && n == 0) || (params[:offset].to_s == (n * Post::PER_PAGE).to_s) %>
      <%= "Page #{n+1}" %>
    <% else %>
      <%= link_to "Page #{n+1}", posts_path(offset: (n * Post::PER_PAGE)) %>
    <% end %>
  <% end %>
  </h5>
</div>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create a new post' %>

<div class='well'>
<%= render 'form' %>
</div>

app/views/posts/show.html.erb
<p class='pull-right'>
  <%= link_to 'Return to index', posts_path %>
  <% if logged_in? && @post.creator == current_user %>
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  <% elsif logged_in? && current_user.admin? %>
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  <% end %>
</p>

<p>
<%= render @post.categories %> 
</p> 

<%= render 'shared/content_title', title: @post.title %>

<p>
  <%= @post.description %>
</p>
<hr/>

<%= render 'shared/errors', entry: @comment %>

<% if logged_in? %>
  <h5>Create a comment:</h5>
  <%= form_for [@post, @comment] do |f| %>
    <%= f.text_area :body, rows: 3, class: "span5" %>
    <br/>
    <%= f.submit "Add comment", class: 'btn btn-primary' %>
  <% end %>
<% end %>

<% unless @post.comments.count == 0 %>
  <h5>Comments</h5>
  <% @post.reload.comments.each do |comment| %>
    <%= render 'comments/comments', comment: comment %>
  <% end %>
<% end %>

app/views/posts/vote.js.erb
$('#post_<%= @post.to_param %>_votes').html('<%= @post.total_votes %> Votes');
<% if @vote.valid? %>
<% else %>
  $('#post_vote_error_<%= @post.to_param %>').show();
<% end %>