config/routes.rb
 PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get '/pin', to: 'sessions#pin'
  post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do 
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end 
    end

  end

  resources :categories, only: [:new, :create, :show]
  resources :users, only: [:show, :create, :edit, :update]
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Slugable

  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true, uniqueness: true

  slugable_column :name

end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update]
  before_action :require_user, except: [:index, :show]
  before_action :require_moderator, only: [:new, :create]


  def index
    @categories = Category.all 
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Your category was added"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end
  
  def edit
  end

  def update
    if @category.update(category_params)
      flash[:notice] = " The category was updated successfully"
      redirect_to categories_path
    else
      render :edit
    end
  end
  
  private
    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find_by(slug: params[:id])
    end

end

app/views/categories/_category.html.erb
<span class="badge"> <%= link_to category.name, category_path(category) %> </span>
<span></span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', entry: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.submit(@category.new_record? ? "Create category" : 'Update category', class: "btn btn-primary") %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/content_title', title: 'Edit Category' %>

<%= render 'form' %>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: 'Categories' %>

<div class = 'well'>
  <p><%= link_to 'Add new', new_category_path %></p>
  <% @categories.each do |category| %>
    <%= category.name %>
    (<%= link_to 'edit', edit_category_path(category) %>)
    <br/>
  <% end %>
</div>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Add a Category' %>

<div class = 'well'>
  <%= render 'form' %>
</div>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe  %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>